# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  blazorhosted:
    image: blazorhosted
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
        - 6080:80
        - 6443:443
  
